apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tfc-agent-app
  namespace: argocd
spec:
  project: default
  source:
    path: base
    repoURL: https://github.com/yohanb/argocd-tfc-agent
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: tfc-agents
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true