apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfc-agents
  labels:
    app: tfc-agents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfc-agents
  template:
    metadata:
      labels:
        app: tfc-agents
    spec:
      containers:
        - name: tfc-agent
          image: hashicorp/tfc-agent:1.2.3
