apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

secretGenerator:
  - name: tfc
    envs:
      - tfc.env
    type: Opaque

patchesStrategicMerge:
  - tf-agents-deployment-env-from.patch.yaml

images:
  - name: tf-agent
    newTag: 1.2.3

replicas:
  - name: tf-agents
    count: 1