apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-secret.yaml
  - deployment.yaml

patchesStrategicMerge:
  - tfc-agents-deployment-env-from.patch.yaml

images:
  - name: tfc-agent
    newTag: 1.2.3

replicas:
  - name: tfc-agents
    count: 1