apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: tfc
spec:
  encryptedData:
    TFC_AGENT_TOKEN: AgDCfFZ7+EvjY2KT1esxfHNzTZq1AfOHBu0CMt08cAN5jpOaPvYT9BV6LDWnbOQlDPWEud+dstAqqUX5K/e0YaaWUC63xMjnYXrF1ZjhZg2PYRFzwo7eHKmVuVHxBpOEzWwHCdo+SxdcKSlP8G+3uEIW8+ooEDfyIks6CMF2t/KvsSWeOLLQDUMwR0Ch3YEKJQ3pBr2H2FxDoGWQrNUcqO65+to6scgb16TsXCerDULFvliW+tRRIr6XdJUrfXPQ/5fNyjypReVPpqLPrNAUrSkWcp54jV7vARDKY/6esODsgIfl7SYkcg/J4KzFrhL6FiFVCgYYMN+COvksBVfU499ifponmN2SZ6WHgIZZlHthxJny64fyGN/VY4u/rNaT/pjKJH08yzSOf9SpiUM2fuXAujDYCum/6gO49KbVLsniQfHQ9Z+nKqcK7e6WtiR03yhHlVx5iy4NZTheznb5boUFpWcTnFireGVt1Hn0z5U1g0KfDbuKTjfuA9EXoMPwCW79XzhwbhP/VA7TVcIGFSSErBEed6N2EwhmCDyIwunrA6o+/mkaxrjQ1THFHUH1BshDqAGoIPqtCWu9whCry58TahgkkMd8W/Lf3L1E/QQltrY6Zhh4ynqoJ75T4OjekjXn3qIhhpP0lXhCEgeH33h10AKFixsK0GXm9C+1/XGjsoMcrtZ2JZnGzwjEDUsMNsc3920n7zRB8ZLD2/8kCDbQhd+ZPyQj0hVPI93FWY0q3d/mgab9nQaLcSfcQiz48aBP43QrzzIOzmd4adzjsuG3V+xGCNVSLsre9F6dfKmPZ5+c8Thfi7lS1uc=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: tfc

