apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-agents
spec:
  template:
    spec:
      containers:
        - name: tf-agent
          envFrom:
            - secretRef:
                name: tfc