apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfc-agents
spec:
  template:
    spec:
      containers:
        - name: tfc-agent
          envFrom:
            - secretRef:
                name: tfc